create table if not exists public.cymatic_reference_assets (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  note_key text,
  source_path text not null,
  public_image_path text,
  asset_status text not null default 'source_screenshot'
    check (asset_status in ('source_screenshot', 'cropped_ready')),
  sort_order integer not null default 0,
  crop_notes text,
  created_at timestamptz not null default timezone('utc', now())
);

insert into public.cymatic_reference_assets (
  slug,
  note_key,
  source_path,
  public_image_path,
  asset_status,
  sort_order,
  crop_notes
)
values
  (
    'cymatic-note-chart',
    null,
    '/cymatics/cymatic-note-chart.webp',
    '/cymatics/cymatic-note-chart.webp',
    'cropped_ready',
    0,
    'Master note-frequency cymatic chart added on 2026-03-23. Use as shared fallback reference until per-note crops are mapped.'
  ),
  (
    'cymatic-source-01',
    null,
    '/cymatics/source/cymatic-source-01.png',
    '/cymatics/source/cymatic-source-01.png',
    'source_screenshot',
    1,
    'Original file: Screenshot 2026-03-23 7.35.00 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-source-02',
    null,
    '/cymatics/source/cymatic-source-02.png',
    '/cymatics/source/cymatic-source-02.png',
    'source_screenshot',
    2,
    'Original file: Screenshot 2026-03-23 7.35.07 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-source-03',
    null,
    '/cymatics/source/cymatic-source-03.png',
    '/cymatics/source/cymatic-source-03.png',
    'source_screenshot',
    3,
    'Original file: Screenshot 2026-03-23 7.35.17 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-source-04',
    null,
    '/cymatics/source/cymatic-source-04.png',
    '/cymatics/source/cymatic-source-04.png',
    'source_screenshot',
    4,
    'Original file: Screenshot 2026-03-23 7.35.39 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-source-05',
    null,
    '/cymatics/source/cymatic-source-05.png',
    '/cymatics/source/cymatic-source-05.png',
    'source_screenshot',
    5,
    'Original file: Screenshot 2026-03-23 7.35.44 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-source-06',
    null,
    '/cymatics/source/cymatic-source-06.png',
    '/cymatics/source/cymatic-source-06.png',
    'source_screenshot',
    6,
    'Original file: Screenshot 2026-03-23 7.35.51 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-source-07',
    null,
    '/cymatics/source/cymatic-source-07.png',
    '/cymatics/source/cymatic-source-07.png',
    'source_screenshot',
    7,
    'Original file: Screenshot 2026-03-23 7.35.57 AM.png. Pending crop to cymatic-only image and note assignment.'
  ),
  (
    'cymatic-note-c',
    'C',
    '/cymatics/notes/C.png',
    '/cymatics/notes/C.png',
    'cropped_ready',
    101,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-c-sharp',
    'C#',
    '/cymatics/notes/C-sharp.png',
    '/cymatics/notes/C-sharp.png',
    'cropped_ready',
    102,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-d',
    'D',
    '/cymatics/notes/D.png',
    '/cymatics/notes/D.png',
    'cropped_ready',
    103,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-d-sharp',
    'D#',
    '/cymatics/notes/D-sharp.png',
    '/cymatics/notes/D-sharp.png',
    'cropped_ready',
    104,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-e',
    'E',
    '/cymatics/notes/E.png',
    '/cymatics/notes/E.png',
    'cropped_ready',
    105,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-f',
    'F',
    '/cymatics/notes/F.png',
    '/cymatics/notes/F.png',
    'cropped_ready',
    106,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-f-sharp',
    'F#',
    '/cymatics/notes/F-sharp.png',
    '/cymatics/notes/F-sharp.png',
    'cropped_ready',
    107,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-g',
    'G',
    '/cymatics/notes/G.png',
    '/cymatics/notes/G.png',
    'cropped_ready',
    108,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-g-sharp',
    'G#',
    '/cymatics/notes/G-sharp.png',
    '/cymatics/notes/G-sharp.png',
    'cropped_ready',
    109,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-a',
    'A',
    '/cymatics/notes/A.png',
    '/cymatics/notes/A.png',
    'cropped_ready',
    110,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-a-sharp',
    'A#',
    '/cymatics/notes/A-sharp.png',
    '/cymatics/notes/A-sharp.png',
    'cropped_ready',
    111,
    'Final note-specific cymatic asset derived from the master chart.'
  ),
  (
    'cymatic-note-b',
    'B',
    '/cymatics/notes/B.png',
    '/cymatics/notes/B.png',
    'cropped_ready',
    112,
    'Final note-specific cymatic asset derived from the master chart.'
  )
on conflict (slug) do update
set
  note_key = excluded.note_key,
  source_path = excluded.source_path,
  public_image_path = excluded.public_image_path,
  asset_status = excluded.asset_status,
  sort_order = excluded.sort_order,
  crop_notes = excluded.crop_notes;
